### ISSUE TITLE
update status of payment if approval is fast

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/procedures#5]
When approval is fast, CPM maybe fail just like order 5e68f6277e6552461488500a that a difference between a creation and a payment is less than 3 seconds

**Comment by matheusgnreis** [comment]
@leomp12

**Comment by leomp12** [comment]
Note: must check

**Comment by leomp12** [comment]
https://github.com/ecomplus/procedures/blob/master/CHANGELOG.md#031-2020-03-18

Not about approval time at all, I think it was happening due to 503 API errors (DDoS).
Keep observing :eyes:
