### ISSUE TITLE
Pedido aprovado não teve entrada no financial_status

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/procedures#9]
Pedido teve as notificações no payment_history, conforme o json:

```
"payments_history": [
    {
      "transaction_id": "5f7b785f7430f92180fa951b",
      "date_time": "2020-10-05T19:47:43.184Z",
      "status": "paid",
      "flags": [
        "cpm"
      ],
      "customer_notified": false,
      "_id": "5f7b786e7430f92180fa9530"
    },
    {
      "status": "paid",
      "date_time": "2020-10-05T19:47:43.184Z",
      "flags": [
        "checkout"
      ],
      "customer_notified": true,
      "_id": "5f7b785f7430f92180fa951d"
    },
    {
      "transaction_id": "5f7b785f7430f92180fa951b",
      "date_time": "2020-10-05T19:47:49.278Z",
      "status": "paid",
      "notification_code": "6510815372",
      "flags": [
        "mercadopago"
      ],
      "customer_notified": false,
      "_id": "5f7b78657430f92180fa9528"
    }
  ]
```
Mas não teve nada relacionado ao financial_status e assim, no painel mostra que não possui status de aprovado.
Pedido 5f7b785c7430f92180fa9517 e ID da loja 1119

**Comment by leomp12** [comment]
Vi este problema ontem à noite e corrigi, fixei em algumas lojas que vi, se puder conferir outras por favor.
Não é um erro do app especificamente, o problema é que a fila ficou grande neste horário e o proxy começou a bloquear muito e não deu vazão.
A solução ideal é essa https://github.com/ecomplus/procedures/issues/6 , mas por enquanto adicionei exceções e dei uma ajustada no proxy.
